dist: xenial
language: node_js
node_js:
  - "10"
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['cmake', 'g++-5']
cache:
  cargo: true
  yarn: true
  directories:
    - node_modules
compiler:
  - clang
before_install:
  - curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain=nightly -y
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$HOME/.cargo/bin:$(yarn global bin):$PATH
  - yarn add @plugnet/dev@latest -W
script:
  - yarn plugnet-dev-travis-build
branches:
  only:
    - master
#deploy:
#  skip_cleanup: true
#  provider: script
#  script: yarn polkadot-dev-travis-deploy
#  on:
#tags: true
